### ISSUE TITLE
Sign-in with Google temporarily disabled

### ISSUE THREAD

**Issue by ben-hogoboom-clutter** [alexwforsythe/code-blocks#119]
Hello!

I am trying to install Code Blocks but when you attempt to give permission to install Google serves the following error:
<img width="646" alt="Screen Shot 2019-11-07 at 5 34 15 PM" src="https://user-images.githubusercontent.com/52930981/68442117-e48d5580-0184-11ea-81f5-28a181032ae6.png">

**Comment by relbekri** [comment]
same for me

**Comment by alexwforsythe** [comment]
Hey y'all. Thanks for letting me know!

I believe this is happening because the add-on needs to be submitted to Google for OAuth API verification. It looks like we've hit an API quota for unverified apps, and that's preventing more users from signing in. I'll do my best to get the app submitted today, but it still may take several days for it to be approved. Sorry for the inconvenience!

More info: https://support.google.com/cloud/answer/7454865

**Comment by alexwforsythe** [comment]
I've add a privacy policy and terms of service and submitted the project to Google for OAuth API verification. Hopefully it's approved soon! 🤞I'll update the issue when I hear back.

**Comment by morrinene** [comment]
Thank you for following up! I cruised by here today to check on this when I couldn't install it on a new Google domain.

**Comment by alexwforsythe** [comment]
Quick update:

Google replied to the verification request today to let me know that the privacy policy and TOS need to be hosted on an authorized domain, which means we can't use the GitHub pages domain (*.github.io).

I've authorized my personal domain in Google's Search Console, pointed the GitHub pages to it, and resubmitted the app for verification. Hoping to hear by by tomorrow!

**Comment by sandy0202020** [comment]
And news? I really need the function..

**Comment by bumper21** [comment]
Still not working, any updates?

**Comment by AdamRj-765** [comment]
Google, this is Adam Rodriguez of IBM Deep Blue -ai search engine decisions team. Were waiting on this app too but quite frankly, I don't see how we can recommend a engine like yours if you cant even approve a simple document api in less than 72 hours for 700k users. I'm afraid were going to have to recommend yahoo as the leading search engine. I hope your api team knows what capitol loss means. See you guys in the stone age.

**Comment by calypsow777** [comment]
Any news ?

**Comment by alexwforsythe** [comment]
Hey everybody. I apologize that the app has remained unavailable for this long. Code Blocks was approved by Google on 11/12, but obviously the issue is still affecting users. The API team and I have been emailing back and forth to find a resolution for about 2 weeks, but they haven't been able to provide me with a solution. Here's a breakdown of what's been happening:
1. I resubmitted the add-on for verification with updated TOS and privacy policy links
2. The add-on was approved by Google, but the "Sign-in with Google temporarily disabled" error continued even after 24 hours
3. I asked the API team to investigate, and they insisted that I record a YouTube video displaying the issue and how my app uses permission scopes
4. I sent them the video
5. They claimed my app uses more OAuth scopes that were originally approved and that I need to resubmit the verification request with more scopes
6. I provided proof that my app only uses the 2 OAuth scopes described in `appsscript.json`
7. In response, they recommended I instead **remove** one of the 2 scopes from my verification request and resubmit
8. I replied with more evidence that my app indeed only uses the 2 OAuth scopes that it was *already* approved for and again asked them to investigate the issue and advise

During the exchange, an unnamed Google rep would typically reply within 24 hours of my emails. As of today, I haven't received a response in 5 days. Overall, I'm disappointed with the support I've received from Google and the in G Suite app developer experience in general.

I will send a follow up email to the API team asking for help on this issue. If they don't reply within 48 hours, I'll resubmit the app for approval with the additional scopes they recommended in `#5`.

**Comment by lptr** [comment]
Thanks for the transparency, hope this gets resolved quickly.

**Comment by Lorkios** [comment]
Thank you for the update!

**Comment by alexwforsythe** [comment]
Hey everybody! Code Blocks should be working again.

I resubmitted Code Blocks for verification a few days ago with an additional OAuth scope (`https://www.googleapis.com/auth/script.scriptapp`) added to the request. The project was reapproved today, and since then the "Sign in with Google temporarily disabled for this app" error appears to be gone.

It's still a complete mystery to me why the additional scope is required, but 🤷‍♂. I was able to install the add-on with a new Google account in a private browser window. Please let me know if you run into any more issues. Cheers!
