### ISSUE TITLE
Google Security Checkup says this has an "Unverified developer"

### ISSUE THREAD

**Issue by xylo04** [alexwforsythe/code-blocks#124]
[Google Security Checkup](https://myaccount.google.com/security-checkup) has flagged this app for me because it has an "unverified developer." Is it easy to go through verification?

**Comment by AdrianHordyk** [comment]
Same issue. Can't install the add-on because app isn't verified

**Comment by npsantini** [comment]
I am having the same issue. Here is what the error looks like.
![image](https://user-images.githubusercontent.com/5314710/68618040-7d2e1900-0496-11ea-9744-9972f2d05e1c.png)

**Comment by frankyn** [comment]
+1, I'm experiencing this as well.

**Comment by alexwforsythe** [comment]
Hey everybody! Thanks for letting me know. I've submitted the app for verification, so we're just waiting for approval from Google's Cloud Platform/API team. See #119 for more details and updates.

**Comment by AdamRj-765** [comment]
I hope they hurry up and get their sh*&^ together.  I have a proposal due in a week. Your app is the only Code Blocks app in G Suite Marketplace and my app has been unavailable due to this error a lot longer than 17 days ago, and you have 746,877 users with an 87% approval rate. They better hurry up man. So common Google Cloud Platform/API wanna be team!! (and this is directly to the team lead @Google) Get your asses in gear!! 746,877 of us are waiting for your bulls&*$ approval.

**Comment by alexwforsythe** [comment]
Hi guys.

**Comment by alexwforsythe** [comment]
See #119 for updates
