### ISSUE TITLE
Please add robotC and gml

### ISSUE THREAD

**Issue by masterarrow4** [alexwforsythe/code-blocks#15]
For users who use the RobotC language for Vex Robotics or equivalents, and for those who use Game Maker's custom language. This would be incredibly helpful.

**Comment by alexwforsythe** [comment]
code-blocks uses [highlight.js](https://github.com/isagalaev/highlight.js/) for all syntax highlighting, so we can only add languages supported by that library. Unfortunately, ROBOTC and GML aren't implemented yet. You can see a list of supported languages [here](https://highlightjs.org/download/).

Due to our complete reliance on that library, I will refer to their position on requesting new languages: http://highlightjs.readthedocs.io/en/latest/language-requests.html
