### ISSUE TITLE
Indentation for cpp

### ISSUE THREAD

**Issue by Mebsworth** [alexwforsythe/code-blocks#42]
I have a block of cpp code that I'm trying to format with Code Blocks. When I format it, the color/font changes apply, but with no indentation. Not sure if this functionality hasn't been added yet or if I'm doing something wrong.

**Comment by alexwforsythe** [comment]
Hi Maya,

I recently updated the add-on description in the Chrome Web Store to reflect this, but Code Blocks was only ever meant to apply syntax highlighting. That means whatever code you want to highlight needs to be formatted correctly before using the add-on.

You aren't the first one to ask this, so I'm starting to wonder why people expect Code Blocks to handle code formatting. Do you think it's because the main button says **Format**? I'm curious to hear your thoughts if you'd like to share.

**Comment by alexwforsythe** [comment]
Closing this out. Feel free to keep commenting if you want.
