### ISSUE TITLE
Pressing Tab has strange behavior

### ISSUE THREAD

**Issue by vityou** [alexwforsythe/code-blocks#51]
When I press Tab, it inserts an un-deletable newline and I have to ctrl-z to delete it.

**Comment by nitingupta910** [comment]
code-blocks creates a 1-table cell when formatting selections that begin and end with empty lines. When tab is pressed, google docs inserts a new row which appears as un-deletable newline since table borders are set to 0-pt by this plugin.

For selections within a line, this plugin does not create a table and tab behavior is as expected.

I don't understand why does this plugin ever use that 1-cell table and why not simple replace selection with formatted input as text **without** any tables.

**Comment by nitingupta910** [comment]
btw, just learnt that you can insert tab in a table using 'Ctrl + ]' on PC, or 'Command + ]' on mac.

**Comment by alexwforsythe** [comment]
Great explanation @nitingupta910. Thanks!

As for why the 1x1 table is used, there are several reasons:
* Cells have a more consistent background color when multiple lines are formatted
* Tables can be deleted easily (<kbd>Right-click</kbd>><kbd>Delete table</kbd>)
* Cells can be reformatted easily by placing the cursor anywhere within the cell, changing the theme, and reselecting <kbd>Format</kbd> (see #9 & #38)

As of now, I don't have any plans to change that behavior.
