### ISSUE TITLE
Add support for JSX and flow

### ISSUE THREAD

**Issue by kevinbarabash** [alexwforsythe/code-blocks#56]
I just started using CodeBlocks and I'm loving it but all of my code examples are JSX + flow so some things have no highlighting.

**Comment by alexwforsythe** [comment]
code-blocks uses [highlight.js](https://github.com/isagalaev/highlight.js/) for all syntax highlighting, so we can only add languages supported by that library. Unfortunately, JSX and flow aren't implemented yet. You can see a list of supported languages [here](https://highlightjs.org/download/).

Due to our dependency on that library, I will refer to their position on requesting new languages: http://highlightjs.readthedocs.io/en/latest/language-requests.html
